# Dockerfile.n8n
FROM n8nio/n8n:1.102.3

# ثبّت node التطويريّ لـ Evolution API
RUN npm install --no-save n8n-nodes-evolution-api

# (اختياري) إن كنت تستخدم Typescript nodes وتحتاج بناء
# RUN n8n-node-dev build --install

