version: '3'
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.7   # أو أي إصدار تختاره من v1.x
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.evo                       # ملف المتغيّرات الخاص بالإصدار v1
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances

volumes:
  evolution_store:
  evolution_instances:
